#
#server:
#  port: 8080
#spring:
#  application:
##    name: "accounts"
#    name: "tender-service"
#  datasource:
#    url: jdbc:h2:mem:./data/tenderdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#  h2:
#    console:
#        enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#springdoc:
#  swagger-ui:
#    path : /docs




#------------------------

server:
  port: 8080
spring:
  application:
    #    name: "accounts"
    name: "tender-service"
  datasource:
    url: jdbc:h2:mem:tenderdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path : /docs